# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "webrick", "~> 1.8"

gem "github-pages", "~> 228"

gem "kramdown-parser-gfm", "~> 1.1"
